version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  frontend-next:
    build: ./frontend-next
    ports:
      - "3000:3000"
    depends_on:
      - bull-board-app
  bull-board-app:
    build: ./bull-board-app
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - rabbitmq
  consumer-redis-fast:
    build: ./consumer-redis-fast
    depends_on:
      - redis
  consumer-redis-slow:
    build: ./consumer-redis-slow
    depends_on:
      - redis
  consumer-rabbitmq:
    build: ./consumer-rabbitmq
    depends_on:
      - rabbitmq
